// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/email_delivery.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailDeliveryService_SendEmail_FullMethodName = "/EmailDeliveryService/SendEmail"
)

// EmailDeliveryServiceClient is the client API for EmailDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailDeliveryServiceClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type emailDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailDeliveryServiceClient(cc grpc.ClientConnInterface) EmailDeliveryServiceClient {
	return &emailDeliveryServiceClient{cc}
}

func (c *emailDeliveryServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, EmailDeliveryService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailDeliveryServiceServer is the server API for EmailDeliveryService service.
// All implementations must embed UnimplementedEmailDeliveryServiceServer
// for forward compatibility.
type EmailDeliveryServiceServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	mustEmbedUnimplementedEmailDeliveryServiceServer()
}

// UnimplementedEmailDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailDeliveryServiceServer struct{}

func (UnimplementedEmailDeliveryServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailDeliveryServiceServer) mustEmbedUnimplementedEmailDeliveryServiceServer() {}
func (UnimplementedEmailDeliveryServiceServer) testEmbeddedByValue()                              {}

// UnsafeEmailDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailDeliveryServiceServer will
// result in compilation errors.
type UnsafeEmailDeliveryServiceServer interface {
	mustEmbedUnimplementedEmailDeliveryServiceServer()
}

func RegisterEmailDeliveryServiceServer(s grpc.ServiceRegistrar, srv EmailDeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailDeliveryService_ServiceDesc, srv)
}

func _EmailDeliveryService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailDeliveryServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailDeliveryService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailDeliveryServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailDeliveryService_ServiceDesc is the grpc.ServiceDesc for EmailDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmailDeliveryService",
	HandlerType: (*EmailDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailDeliveryService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/email_delivery.proto",
}
