// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/search_filter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchEmailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Labels         []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	DateRangeStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_range_start,json=dateRangeStart,proto3" json:"date_range_start,omitempty"`
	DateRangeEnd   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_range_end,json=dateRangeEnd,proto3" json:"date_range_end,omitempty"`
}

func (x *SearchEmailsRequest) Reset() {
	*x = SearchEmailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmailsRequest) ProtoMessage() {}

func (x *SearchEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmailsRequest.ProtoReflect.Descriptor instead.
func (*SearchEmailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{0}
}

func (x *SearchEmailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchEmailsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchEmailsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SearchEmailsRequest) GetDateRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.DateRangeStart
	}
	return nil
}

func (x *SearchEmailsRequest) GetDateRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.DateRangeEnd
	}
	return nil
}

type SearchEmailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []*Email `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *SearchEmailsResponse) Reset() {
	*x = SearchEmailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmailsResponse) ProtoMessage() {}

func (x *SearchEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmailsResponse.ProtoReflect.Descriptor instead.
func (*SearchEmailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{1}
}

func (x *SearchEmailsResponse) GetEmails() []*Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailId  string                 `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Sender   string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Subject  string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Preview  string                 `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	DateSent *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_sent,json=dateSent,proto3" json:"date_sent,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Email) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *Email) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *Email) GetDateSent() *timestamppb.Timestamp {
	if x != nil {
		return x.DateSent
	}
	return nil
}

type CreateFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sender          string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SubjectContains string `protobuf:"bytes,3,opt,name=subject_contains,json=subjectContains,proto3" json:"subject_contains,omitempty"`
	MoveToFolder    string `protobuf:"bytes,4,opt,name=move_to_folder,json=moveToFolder,proto3" json:"move_to_folder,omitempty"`
}

func (x *CreateFilterRequest) Reset() {
	*x = CreateFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRequest) ProtoMessage() {}

func (x *CreateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFilterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFilterRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *CreateFilterRequest) GetSubjectContains() string {
	if x != nil {
		return x.SubjectContains
	}
	return ""
}

func (x *CreateFilterRequest) GetMoveToFolder() string {
	if x != nil {
		return x.MoveToFolder
	}
	return ""
}

type CreateFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterId string `protobuf:"bytes,1,opt,name=filter_id,json=filterId,proto3" json:"filter_id,omitempty"`
}

func (x *CreateFilterResponse) Reset() {
	*x = CreateFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterResponse) ProtoMessage() {}

func (x *CreateFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterResponse.ProtoReflect.Descriptor instead.
func (*CreateFilterResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFilterResponse) GetFilterId() string {
	if x != nil {
		return x.FilterId
	}
	return ""
}

type ApplyFiltersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ApplyFiltersRequest) Reset() {
	*x = ApplyFiltersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFiltersRequest) ProtoMessage() {}

func (x *ApplyFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFiltersRequest.ProtoReflect.Descriptor instead.
func (*ApplyFiltersRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyFiltersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ApplyFiltersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilteredEmails []*FilteredEmail `protobuf:"bytes,1,rep,name=filtered_emails,json=filteredEmails,proto3" json:"filtered_emails,omitempty"`
}

func (x *ApplyFiltersResponse) Reset() {
	*x = ApplyFiltersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFiltersResponse) ProtoMessage() {}

func (x *ApplyFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFiltersResponse.ProtoReflect.Descriptor instead.
func (*ApplyFiltersResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyFiltersResponse) GetFilteredEmails() []*FilteredEmail {
	if x != nil {
		return x.FilteredEmails
	}
	return nil
}

type FilteredEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailId string `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Folder  string `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
}

func (x *FilteredEmail) Reset() {
	*x = FilteredEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilteredEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilteredEmail) ProtoMessage() {}

func (x *FilteredEmail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilteredEmail.ProtoReflect.Descriptor instead.
func (*FilteredEmail) Descriptor() ([]byte, []int) {
	return file_proto_search_filter_proto_rawDescGZIP(), []int{7}
}

func (x *FilteredEmail) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *FilteredEmail) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

var File_proto_search_filter_proto protoreflect.FileDescriptor

var file_proto_search_filter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x44, 0x0a, 0x10, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x40, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f,
	0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x45, 0x6e, 0x64, 0x22, 0x36, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x37, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x6e, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x29,
	0x0a, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x6f, 0x76,
	0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22,
	0x33, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x64, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x42, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x32, 0xcc, 0x01, 0x0a, 0x13, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_search_filter_proto_rawDescOnce sync.Once
	file_proto_search_filter_proto_rawDescData = file_proto_search_filter_proto_rawDesc
)

func file_proto_search_filter_proto_rawDescGZIP() []byte {
	file_proto_search_filter_proto_rawDescOnce.Do(func() {
		file_proto_search_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_search_filter_proto_rawDescData)
	})
	return file_proto_search_filter_proto_rawDescData
}

var file_proto_search_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_search_filter_proto_goTypes = []any{
	(*SearchEmailsRequest)(nil),   // 0: SearchEmailsRequest
	(*SearchEmailsResponse)(nil),  // 1: SearchEmailsResponse
	(*Email)(nil),                 // 2: Email
	(*CreateFilterRequest)(nil),   // 3: CreateFilterRequest
	(*CreateFilterResponse)(nil),  // 4: CreateFilterResponse
	(*ApplyFiltersRequest)(nil),   // 5: ApplyFiltersRequest
	(*ApplyFiltersResponse)(nil),  // 6: ApplyFiltersResponse
	(*FilteredEmail)(nil),         // 7: FilteredEmail
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_search_filter_proto_depIdxs = []int32{
	8, // 0: SearchEmailsRequest.date_range_start:type_name -> google.protobuf.Timestamp
	8, // 1: SearchEmailsRequest.date_range_end:type_name -> google.protobuf.Timestamp
	2, // 2: SearchEmailsResponse.emails:type_name -> Email
	8, // 3: Email.date_sent:type_name -> google.protobuf.Timestamp
	7, // 4: ApplyFiltersResponse.filtered_emails:type_name -> FilteredEmail
	0, // 5: SearchFilterService.SearchEmails:input_type -> SearchEmailsRequest
	3, // 6: SearchFilterService.CreateFilter:input_type -> CreateFilterRequest
	5, // 7: SearchFilterService.ApplyFilters:input_type -> ApplyFiltersRequest
	1, // 8: SearchFilterService.SearchEmails:output_type -> SearchEmailsResponse
	4, // 9: SearchFilterService.CreateFilter:output_type -> CreateFilterResponse
	6, // 10: SearchFilterService.ApplyFilters:output_type -> ApplyFiltersResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_search_filter_proto_init() }
func file_proto_search_filter_proto_init() {
	if File_proto_search_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_search_filter_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchEmailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchEmailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyFiltersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyFiltersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_filter_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FilteredEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_search_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_filter_proto_goTypes,
		DependencyIndexes: file_proto_search_filter_proto_depIdxs,
		MessageInfos:      file_proto_search_filter_proto_msgTypes,
	}.Build()
	File_proto_search_filter_proto = out.File
	file_proto_search_filter_proto_rawDesc = nil
	file_proto_search_filter_proto_goTypes = nil
	file_proto_search_filter_proto_depIdxs = nil
}
